#pragma once

#include "follow.h"
#include "gcorr.h"
#include "gofr.h"
#include "gtcorr.h"
#include "highlight.h"
#include "histo.h"
#include "momentum.h"
#include "persistence.h"
#include "pofr.h"
#include "pvt.h"
#include "shift2com.h"
#include "svden.h"
#include "svt.h"
#include "sxyzc.h"
#include "varden.h"